cmd: 'echo "Pick a command (see .atom-build.yml)"'
name: ''
targets:
  Build RPi4 snapshot in toolbox:
    cmd: 'buildWrapper toolboxRun -c openwrt {FILE_ACTIVE} --version snapshot --target brcm2708/bcm2711 --profile rpi-4 --ssh-backup root@192.168.2.1'
  Build Archer snapshot in toolbox:
    cmd: 'buildWrapper toolboxRun -c openwrt {FILE_ACTIVE} --version "snapshot" --target "brcm2708/bcm2711" --profile "rpi-4" --ssh-backup "root@192.168.2.1"'
